language: php

sudo: false

php:
  - 5.6
  - 7.1

env:
  global:
    - DEFAULT=1

matrix:
  include:
    - php: 7.0
      env: PHPCS=1 DEFAULT=0

  fast_finish: true

  allow_failures:
    - php: 5.6
    - php: 7.1
 
before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction

script:
  - sh -c "if [ '$DEFAULT' = '1' ]; then vendor/bin/phpunit ; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then composer cs-check ; fi"

notifications:
  email: false
