language: php

sudo: false

php:
  - 7.1

env:
  global:
    - DEFAULT=1

matrix:
  include:
    - php: 7.2
      env: PHPCS=1 DEFAULT=0

  fast_finish: true

install:
  - composer install --prefer-dist --no-interaction

script:
  - if [ '$DEFAULT' = '1' ]; then vendor/bin/codecept run; fi
  - if [ '$PHPCS' = '1' ]; then vendor/bin/phpcs --standard=vendor/spryker/code-sniffer/Spryker/ruleset.xml -v src/ tests/ ; fi

notifications:
  email: false
