language: php

sudo: false

php:
  - 7.1
  - 7.2

env:
  global:
    - DEFAULT=1

matrix:
  include:
    - php: 7.1
      env: PREFER_LOWEST=1
  
    - php: 7.2
      env: CHECKS=1 DEFAULT=0

  fast_finish: true

before_script:
  - if [[ $PREFER_LOWEST != 1 ]]; then composer install --prefer-source --no-interaction ; fi
  - if [[ $PREFER_LOWEST == 1 ]]; then composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable ; fi

script:
  - if [[ $DEFAULT == 1 ]]; then vendor/bin/codecept run ; fi
  - if [[ $CHECKS == 1 ]]; then composer cs-check ; fi

notifications:
  email: false
